########################################################################################################
################################## 设置 Spring Boot 容器端口##############################################
########################################################################################################
server:
  port: 2010
  tomcat:
    uri-encoding: UTF-8


